### ISSUE TITLE
 IndexError: too many indices for tensor of dimension 3

### ISSUE THREAD

**Issue by greengerong** [sethgggg/sd-webui-hunyuan-dit#1]
error with:
```
    Traceback (most recent call last):
      File "/mnt/d/project/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/mnt/d/project/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/modules/txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "/mnt/d/project/stable-diffusion-webui/modules/processing.py", line 845, in process_images
        res = process_images_inner(p)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-hunyuan-dit/scripts/hunyuandit.py", line 490, in process_images_inner_hunyuan
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-hunyuan-dit/scripts/hunyuandit.py", line 26, in sample_txt2img
        prompt_embeds = tensor["crossattn"]
    IndexError: too many indices for tensor of dimension 3
```

How to fix? 
Thanks

**Comment by prefectgou** [comment]
I have encountered a common issue, which should be that you have enabled the HunyuanDiT tab. You can try closing this tab

**Comment by prefectgou** [comment]
I have encountered a common issue, which should be that you have enabled the HunyuanDiT tab. You can try closing this tab

**Comment by Idiosyncras** [comment]
关掉Enable Hunyuan DiT ，生图就灰色图片，开了就IndexError: too many indices for tensor of dimension 3 报错

**Comment by weilin9999** [comment]
我也遇到了你这个问题不知道什么原因
